services:
  suppl-ai:
    extends:
      file: ./Suppl-AI/docker-compose.yml
      service: suppl-ai
    container_name: suppl-ai

  llm-api:
    extends:
      file: ./LLM-API/docker-compose.yml
      service: llm-api
    container_name: llm-api

  database-api:
    extends:
      file: ./Database-API/docker-compose.yml
      service: api
    container_name: database-api
    
  mongo-db:
    extends:
      file: ./Database-API/docker-compose.yml
      service: mongo-db
    container_name: database-mongo
    
  mongo-express:
    extends:
      file: ./Database-API/docker-compose.yml
      service: mongo-express
    container_name: database-mongo-express

volumes:
  mongodb_data:
