const message_dict = [
  'Hello World',
  'I am feeling great today!',
  'The weather is wonderful.',
  'My favorite color is blue.',
  'It\'s great to meet you.',
  'I love traveling to new places.',
  'Do you like to read books?',
  'I enjoy listening to music every day.',
  'It\'s been a busy week for me.',
  'I like to spend my weekends hiking.',
  'Technology is always evolving.',
  'I\'ve been working on some new projects.',
  'The sunrise this morning was beautiful.',
  'I\'m learning to cook new recipes.',
  'It\'s important to stay hydrated.',
  'I enjoy spending time with friends.',
  'Have you ever tried meditation?',
  'Exercise helps me stay healthy.',
  'I just finished watching a great movie.',
  'Life is full of opportunities.',
  'The city is so vibrant at night.',
  'My favorite season is autumn.',
  'I\'m always up for an adventure.',
  'There\'s nothing like a cup of coffee in the morning.',
  'I love trying new cuisines.',
  'Reading books can transport you to another world.',
  'The beach is my happy place.',
  'I believe in the power of kindness.',
  'Sometimes a good laugh is all you need.',
  'I love solving puzzles.',
  'Learning something new every day keeps me motivated.',
  'What a beautiful sunset!',
  'I am passionate about photography.',
  'There\'s always something to be grateful for.',
  'I love to spend my free time painting.',
  'Today is a good day to start a new project.',
  'Music has the power to change your mood.',
  'A great day starts with a positive mindset.',
  'I enjoy spending time in nature.',
  'It\'s important to take breaks throughout the day.',
  'Traveling opens up new perspectives.',
  'There are so many books I want to read.',
  'I\'m learning to speak another language.',
  'It\'s important to stay curious.',
  'I can\'t wait to see what tomorrow brings.',
  'The world is full of amazing places.',
  'Every day is a new opportunity to grow.',
  'I enjoy helping others.',
  'Sometimes, the best moments are the quiet ones.',
  'I love the smell of fresh flowers.',
  'Being creative is so fulfilling.',
  'Today is a great day for a walk.',
  'Laughter truly is the best medicine.',
  'I love watching the stars at night.',
  'Music is a universal language.',
  'I\'m working on improving my skills.',
  'I believe in the power of positivity.',
  'The mountains are calling.',
  'I enjoy exploring new cities.',
  'There\'s nothing like a good cup of tea.',
  'I enjoy learning about different cultures.',
  'Life is better when you\'re surrounded by good friends.',
  'I believe in the importance of self-care.',
  'I love to write in my journal.',
  'Good things come to those who wait.',
  'The future is full of possibilities.',
  'I am grateful for every opportunity I have.',
  'Chasing your dreams is worth it.',
  'It\'s always a good time to start something new.',
  'Nature has a calming effect.',
  'I enjoy spending time in the kitchen.',
  'Sometimes it\'s good to take a break and relax.',
  'I love the sound of the ocean waves.',
  'I believe in setting goals and achieving them.',
  'It\'s always nice to receive a compliment.',
  'There\'s no place like home.',
  'I enjoy trying new activities.',
  'I\'m working on being more mindful every day.',
  'I appreciate the small things in life.',
  'Life is full of surprises.',
  'It\'s important to take care of your mental health.',
  'The best moments are often the simplest ones.',
  'I love the sound of birds chirping in the morning.',
  'Taking risks is how we grow.',
  'I enjoy exploring new hobbies.',
  'The sky is so clear tonight.',
  'There\'s always something new to learn.',
  'I\'m looking forward to the weekend.',
  'There\'s no limit to what you can achieve.',
  'I love experiencing new adventures.',
  'The journey is just as important as the destination.',
  'I enjoy spending time at a coffee shop.',
  'Today is a great day to be productive.',
  'I enjoy spending time with my family.',
  'Happiness is a choice.',
  'It\'s important to stay true to yourself.',
  'I believe that everything happens for a reason.',
  'A positive attitude makes all the difference.',
  'There\'s always a way to improve.',
  'I love the feeling of accomplishment.',
  'It\'s nice to take a moment to appreciate the present.',
  'I believe in the power of hard work.',
  'There\'s always room for growth and improvement.',
  'I\'m grateful for the support of my friends.',
  'Life is about the journey, not the destination.',
  'I love learning about history.',
  'The night sky is so peaceful.',
  'I believe in following your dreams.',
  'It\'s always good to have a plan.',
  'Every experience teaches us something new.',
  'Taking time to relax is essential.',
  'I enjoy working on creative projects.',
  'I love trying new foods.',
  'Success comes with perseverance.',
  'It\'s important to appreciate the people around you.'
];

export default function generateChatMessages() {
  let messages: string = "";
  const random = (min:number,max:number)=> Math.floor(Math.random() * (max - min + 1) + min);
  for (let i = 0; i < random(1,5); i++) {
    const randomIndex = Math.floor(Math.random() * message_dict.length);
    messages += message_dict[randomIndex] + " ";
  }
  return messages;
}